#!/bin/bash

set -Eeuo pipefail

trap "pkill -P $$" EXIT

if [ -z ${1+x} ]; then
  echo "Usage: scripts/dev <game-path>"
  echo
  echo "<game-path> is missing!"
  echo
  exit 1
fi

cd site
yarn
npm run build
cd -
$(cd site && npm run build:watch) &
LIVE_DEV=1 go run cmd/main.go run -root "$1"
