#!/bin/bash

set -e

if [ -z ${GITHUB_TOKEN+x} ]; then
  echo "You need to supply a GITHUB_TOKEN env variable before you can publish"
  echo
  exit 1
fi

git update-index --really-refresh
git diff-index --quiet HEAD
./scripts/check
tag=$(jq '.version' package.json -r)
echo $tag
git tag -a "v${tag}" -m"Release version ${tag}"
goreleaser release --clean
git push --tags
