#!/bin/bash

set -e

git update-index --really-refresh
git diff-index --quiet HEAD
./scripts/check
tag=$(jq '.version' package.json -r)
echo $tag
git tag -a "v${tag}" -m"Release version ${tag}"
goreleaser release --clean
git push --tags
