on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
name: Check
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v4
      with:
        go-version-file: 'go.mod'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 18.18.2
    - run: cd site && yarn
    - run: cd site && yarn build
    - run: go install golang.org/x/vuln/cmd/govulncheck@latest
    - name: Run Gosec Security Scanner
      uses: securego/gosec@master
      with:
        args: ./...
    - run: go vet ./...
    - run: govulncheck ./...
